### ISSUE TITLE
Unable to load asset due to prepended asset path.

### ISSUE THREAD

**Issue by zlu** [arrrrny/tesseract_ocr#40]
on M1
flutter:   Error Value: Unable to load asset: "assets/tessdata/assets/tessdata/chi_sim.traineddata".

with the configurations:

pubspec.yaml
  assets:
    - assets/
    - assets/tessdata/

tessdata_config.json

{
  "files": [
    "chi_sim.traineddata"
  ]
}

directory structure:

+pubspec.yaml
+assets/tessdata_config.json
+assets/tessdata/chi_cim.traineddata

latest versions of cocoapods gem.

It appears that the plugin might be hard-coding assets/tessdata path and prepending it to the flutter config.

**Comment by zlu** [comment]
this line: if (!await File('$tessdataDirectory/$file').exists()) in class TesseractOcr is prepending the path.

**Comment by arrrrny** [comment]
fixed

**Comment by m-1226** [comment]
not fixed any more 
[log] OCR Error: Unable to load asset: "tessdata/ara.traineddata".
      The asset does not exist or has empty data.

    - assets/tessdata_config.json
    - assets/tessdata/

**Comment by arrrrny** [comment]
@m-1226  do you have that file placed in assets/tessdata/ara.traineddata? 
also try adding this line to the pubspec.yaml as well

- assets/tessdata/ara.traineddata

**Comment by YashOEncureIT** [comment]
yes , I am also facing the issue. Please check logs . @arrrrny @HTMHell @TheLastGimbus 

An exception has occurred.
PlatformException (PlatformException(error, Data path must not be null!, null, java.lang.IllegalArgumentException: Data path must not be null!
	at com.googlecode.tesseract.android.TessBaseAPI.init(TessBaseAPI.java:413)
	at com.googlecode.tesseract.android.TessBaseAPI.init(TessBaseAPI.java:392)
	at com.googlecode.tesseract.android.TessBaseAPI.init(TessBaseAPI.java:377)
	at io.paratoner.tesseract_ocr.TesseractOcrPlugin.onMethodCall(TesseractOcrPlugin.java:47)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8319)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
))
